openapi: 3.0.0
info:
  title: Diff API
  version: 1.0.0
paths:
  /diff/map:
    get:
      summary: Calculate the difference between 'a' and 'b' for mapping.
      parameters:
        - name: a
          in: query
          description: First commit
          required: true
          schema:
            type: string
        - name: b
          in: query
          description: Second commit
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content: 
            application/json:
              schema:
                type: object
                required:
                  - linesTotal
                  - files
                properties:
                  linesTotal:
                    type: integer
                  files:
                    type: array
                    items:
                      $ref: '#/components/schemas/FileDiff'
        '400':
          $ref: '#/components/responses/Error'
  /diff/part:
    get:
      summary: "Get information about partial diff between a and b for given startline and endline"
      parameters:
        - name: a
          in: query
          description: First commit
          required: true
          schema:
            type: string
        - name: b
          in: query
          description: Second commit
          required: true
          schema:
            type: string
        - name: start
          in: query
          description: Start line of the diff
          required: true
          schema:
            type: integer
        - name: end
          in: query
          required: true
          description: End line for the diff
          schema:
            type: integer
      responses:
          '200':
            description: Successful response
            content: 
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/LineDiff'
          '400':
            $ref: '#/components/responses/Error'
components:
  schemas:
    Range:
      type: object
      required:
        - start
        - end
      properties:
        start:
          type: integer
        end:
          type: integer
    LineDiff:
      type: object
      required:
        - op
        - content
        - srcLineNumber
        - dstLineNumber
      properties:
        srcLineNumber:
          type: integer
          format: int64
        dstLineNumber:
          type: integer
          format: int64
        content:
          type: string
        op:
          type: string
          enum:
            - a
            - d
    FileDiff:
      type: object
      required:
        - status
        - src
        - dst
        - lines
        - isBinary
      properties:
        status:
          $ref: '#/components/schemas/Status'
        src:
          $ref: '#/components/schemas/State'
        dst:
          $ref: '#/components/schemas/State'
        isBinary:
          type: boolean
        lines:
          $ref: '#/components/schemas/Range'
    Status:
      type: object
      required:
        - type
      properties:
        score:
          type: integer
          minimum: 0
          maximum: 100
        type:
          type: string
          enum:
            - A
            - C
            - D
            - M
            - R
            - T
            - U
            - X
    State:
      type: object
      required:
        - path
      properties:
        path:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
  responses:
    Error:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'