// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for LineDiffOp.
const (
	LineDiffOpA LineDiffOp = "a"
	LineDiffOpD LineDiffOp = "d"
)

// Defines values for StatusType.
const (
	StatusTypeA StatusType = "A"
	StatusTypeC StatusType = "C"
	StatusTypeD StatusType = "D"
	StatusTypeM StatusType = "M"
	StatusTypeR StatusType = "R"
	StatusTypeT StatusType = "T"
	StatusTypeU StatusType = "U"
	StatusTypeX StatusType = "X"
)

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// FileDiff defines model for FileDiff.
type FileDiff struct {
	Dst    State  `json:"dst"`
	Lines  Range  `json:"lines"`
	Src    State  `json:"src"`
	Status Status `json:"status"`
}

// LineDiff defines model for LineDiff.
type LineDiff struct {
	Content string     `json:"content"`
	Op      LineDiffOp `json:"op"`
}

// LineDiffOp defines model for LineDiff.Op.
type LineDiffOp string

// Range defines model for Range.
type Range struct {
	End   int `json:"end"`
	Start int `json:"start"`
}

// State defines model for State.
type State struct {
	IsBinary bool   `json:"isBinary"`
	Path     string `json:"path"`
}

// Status defines model for Status.
type Status struct {
	Score *int       `json:"score,omitempty"`
	Type  StatusType `json:"type"`
}

// StatusType defines model for Status.Type.
type StatusType string

// GetDiffMapParams defines parameters for GetDiffMap.
type GetDiffMapParams struct {
	// A First commit
	A string `form:"a" json:"a"`

	// B Second commit
	B string `form:"b" json:"b"`
}

// GetDiffPartParams defines parameters for GetDiffPart.
type GetDiffPartParams struct {
	// A First commit
	A string `form:"a" json:"a"`

	// B Second commit
	B string `form:"b" json:"b"`

	// Start Start line of the diff
	Start int `form:"start" json:"start"`

	// End End line for the diff
	End int `form:"end" json:"end"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Calculate the difference between 'a' and 'b' for mapping.
	// (GET /diff/map)
	GetDiffMap(ctx echo.Context, params GetDiffMapParams) error
	// Get information about partial diff between a and b for given startline and endline
	// (GET /diff/part)
	GetDiffPart(ctx echo.Context, params GetDiffPartParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetDiffMap converts echo context to params.
func (w *ServerInterfaceWrapper) GetDiffMap(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDiffMapParams
	// ------------- Required query parameter "a" -------------

	err = runtime.BindQueryParameter("form", true, true, "a", ctx.QueryParams(), &params.A)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter a: %s", err))
	}

	// ------------- Required query parameter "b" -------------

	err = runtime.BindQueryParameter("form", true, true, "b", ctx.QueryParams(), &params.B)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter b: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDiffMap(ctx, params)
	return err
}

// GetDiffPart converts echo context to params.
func (w *ServerInterfaceWrapper) GetDiffPart(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDiffPartParams
	// ------------- Required query parameter "a" -------------

	err = runtime.BindQueryParameter("form", true, true, "a", ctx.QueryParams(), &params.A)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter a: %s", err))
	}

	// ------------- Required query parameter "b" -------------

	err = runtime.BindQueryParameter("form", true, true, "b", ctx.QueryParams(), &params.B)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter b: %s", err))
	}

	// ------------- Required query parameter "start" -------------

	err = runtime.BindQueryParameter("form", true, true, "start", ctx.QueryParams(), &params.Start)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start: %s", err))
	}

	// ------------- Required query parameter "end" -------------

	err = runtime.BindQueryParameter("form", true, true, "end", ctx.QueryParams(), &params.End)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDiffPart(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/diff/map", wrapper.GetDiffMap)
	router.GET(baseURL+"/diff/part", wrapper.GetDiffPart)

}

type ErrorJSONResponse Error

type GetDiffMapRequestObject struct {
	Params GetDiffMapParams
}

type GetDiffMapResponseObject interface {
	VisitGetDiffMapResponse(w http.ResponseWriter) error
}

type GetDiffMap200JSONResponse struct {
	Files      []FileDiff `json:"files"`
	LinesTotal int        `json:"linesTotal"`
}

func (response GetDiffMap200JSONResponse) VisitGetDiffMapResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDiffMap400JSONResponse struct{ ErrorJSONResponse }

func (response GetDiffMap400JSONResponse) VisitGetDiffMapResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDiffPartRequestObject struct {
	Params GetDiffPartParams
}

type GetDiffPartResponseObject interface {
	VisitGetDiffPartResponse(w http.ResponseWriter) error
}

type GetDiffPart200JSONResponse []LineDiff

func (response GetDiffPart200JSONResponse) VisitGetDiffPartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDiffPart400JSONResponse struct{ ErrorJSONResponse }

func (response GetDiffPart400JSONResponse) VisitGetDiffPartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Calculate the difference between 'a' and 'b' for mapping.
	// (GET /diff/map)
	GetDiffMap(ctx context.Context, request GetDiffMapRequestObject) (GetDiffMapResponseObject, error)
	// Get information about partial diff between a and b for given startline and endline
	// (GET /diff/part)
	GetDiffPart(ctx context.Context, request GetDiffPartRequestObject) (GetDiffPartResponseObject, error)
}

type StrictHandlerFunc = runtime.StrictEchoHandlerFunc
type StrictMiddlewareFunc = runtime.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetDiffMap operation middleware
func (sh *strictHandler) GetDiffMap(ctx echo.Context, params GetDiffMapParams) error {
	var request GetDiffMapRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDiffMap(ctx.Request().Context(), request.(GetDiffMapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDiffMap")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDiffMapResponseObject); ok {
		return validResponse.VisitGetDiffMapResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetDiffPart operation middleware
func (sh *strictHandler) GetDiffPart(ctx echo.Context, params GetDiffPartParams) error {
	var request GetDiffPartRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDiffPart(ctx.Request().Context(), request.(GetDiffPartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDiffPart")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDiffPartResponseObject); ok {
		return validResponse.VisitGetDiffPartResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xVy2ojOxD9FVH3gjcidu6dVe/yJjCBkGRgIGQhd1c7Cq1HpOrMmOB/H0qy24+2Y4dh",
	"NrNTS6U6pVOnTr9D6Yx3Fi1FKN4hYPTORkwfFyG4wIvSWUJLvFTeN7pUpJ0dvkRneS+Wz2gUr/4NWEMB",
	"/wyXWYf5NA5zttlsJqHCWAbtOQkUcKoqEfC1xUjAp/MLaxX44DwG0rkwXGzT1CMUECloO0mXOZEOWEHx",
	"OA97koswN37BkmAm4VI3eK7rup+6irTvIfekCDlLo22+9FH0nbKTFB1DeXDmSIraeEh4G3vPnl/OiDK9",
	"aFHrNi6+aruDi5W2bxAtwfnUCNsahlSMs5J9R0OcB9ll3VZLJqvfb1utFKEt4QTDnKdA2476lARmgRNt",
	"w83E93B1PNVWhekKwti5BpXlS17R834Rpii5TLULPrd7HT+WLqSyjPqpDVN9PBpJMNrmr5HcwkneWfbm",
	"BCScgYRzkHADEu5AwgNI+AYSvu/vWTrtF81h2tYuEaCp4TNWkTi5vQYJbxhinu7jo9HRKCsGrfIaCvg/",
	"bWUC0zuHla7roVFJUxNMHWUeks1cV1DAFRJnv1E+3QvKIGGIUDy+b7jJpQ6RROmM0dxxzXuvLYYpSLDK",
	"cJ2s1uUTKbQoVzysR8cmwj2WzlYfQ4w/BfEk1433v9HoU7a7rppaN3P5Epq9JtJZYScdUCGoaWdwD45U",
	"c8CMrQTLeQ3bZbPBZluWGGPdNmLBAUN/yRRsq7yjqvulSIitMWlQ4Uw1ZdsoQkHPKFhYGNCWKMZIPxCt",
	"GKiBULYSg/FA1C4Io7zXdnKU8mQl+rmrfCTF2+wof50W+xDsnYK7K1zdkboDa2G0e/FWVLQJeGGrDMfd",
	"2YPHhv4ptN8dtYNmqvul9mbqz+v/CkmwMQeTniDU2LUkWNFaNYnKbhJUmoNx4nmi39CK1L7EPZ+grXjN",
	"Vc9+BQAA///GPPDMKQoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
